projects:
  fluss_next:
    schema: http://jhnnsrs-lab/fluss/schema
    documents: graphql/*/**.graphql
    extensions:
      turms:
        out_dir: fluss_next/api
        dump_configuration: true
        dump_schema: true
        exclude_typenames: true
        freeze:
          enabled: true
        options:
          enabled: true
          use_enum_values: true
          allow_population_by_field_name: true
          extra: forbid
          types:
            - input
        stylers:
          - type: turms.stylers.default.DefaultStyler
          - type: turms.stylers.appender.AppenderStyler
            append_fragment: ""
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            coercible_scalars:
              ID: rath.scalars.IDCoercible
            expand_input_types:
              - input
            global_kwargs:
              - type: fluss_next.rath.FlussRath
                key: rath
                description:
                  The client we want to use (defaults to the currently active
                  client)
            definitions:
              - type: subscription
                is_async: true
                use: fluss_next.funcs.asubscribe
              - type: query
                is_async: true
                use: fluss_next.funcs.aexecute
              - type: mutation
                is_async: true
                use: fluss_next.funcs.aexecute
              - type: subscription
                use: fluss_next.funcs.subscribe
              - type: query
                use: fluss_next.funcs.execute
              - type: mutation
                use: fluss_next.funcs.execute
        processors:
          - type: turms.processors.disclaimer.DisclaimerProcessor
        scalar_definitions:
          uuid: str
          Callback: str
          Any: typing.Any
          Arg: typing.Any
          ID: rath.scalars.ID
          EventValue: fluss_next.scalars.EventValue
          ValueMap: typing.Dict
          AnyDefault: typing.Any
          ValidatorFunction: fluss_next.scalars.ValidatorFunction
          Identifier: str
          SearchQuery: str
        additional_config:
          EdgeInput:
            allow_population_by_field_name: true
        additional_bases:
          FlowGraph:
            - fluss_next.traits.Graph
          StreamItem:
            - fluss_next.traits.MockableTrait
          StreamItemChild:
            - fluss_next.traits.MockableTrait
  